### ISSUE TITLE
Error when closing plugin

### ISSUE THREAD

**Issue by lachlangrose** [Loop3D/qgis-loopplugin#2]
When opening the plugin clicking load geol layer and then exiting without loading  layer I get the following error.

```
An error has occurred while executing Python code: 

IndexError: list index out of range 
Traceback (most recent call last):
  File "C:\Users/lachl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis-loopplugin-master\loop_plugin_dialog.py", line 101, in activate_layers
    self.path_file    = list_of_files[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users/lachl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis-loopplugin-master\loop_plugin_dialog.py", line 122, in create_geology_IdName
    p,self.GeolPath  = self.activate_layers(self.sender().text())                                    ## This help select the shapefile
  File "C:\Users/lachl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis-loopplugin-master\loop_plugin_dialog.py", line 111, in activate_layers
    self.path_file    = list_of_files[0]
IndexError: list index out of range


```
This suggests to me that there is no check in place to make sure that the user actually selects a file...

**Comment by ShebMichel** [comment]
Issue solved..
